    ['oppressor3'] = {
        ['name'] = 'Oppressor Mark 3',
        ['brand'] = 'custom',
        ['model'] = 'oppressor3',
        ['price'] = 0,
        ['category'] = 'motorcycles',
        ['categoryLabel'] = 'motorcycles',
        ['hash'] = `oppressor3`,
        ['shop'] = 'private',
    },